### Session starten
POST http://localhost:8080/session
Content-Type: application/json

{
  "patient":
  {
    "name": "Hans Peter"
  },
  "kontaktPerson":
  {
    "name": "Heidi Hugo",
    "telefonNummer": "015678615"
  }
}

### Session inkl. Selbsttest starten
POST http://localhost:8080/session
Content-Type: application/json

{
  "patient":
  {
    "name": "Hans Peter"
  },
  "kontaktPerson":
  {
    "name": "Heidi Hugo",
    "telefonNummer": "015678615"
  },
  "selbstTest": {
    "Haben Sie Fieber?":"nein",
    "Haben Sie Husten?": "ja",
    "Wie wohnen Sie?": "allein",
    "datum": "2020-04-20"
  }
}

### Get Session
GET http://localhost:8080/session/{SessionKey}

### Message vom Patienten senden
POST http://localhost:8080/session/{SessionKey}/message
Content-Type: application/json

{
  "nachrichtenText": "Nein",
  "videoPfad": "https://cdn.jwplayer.com/videos/ZHj6MOWJ-3uRaWXX3.mp4",
  "fromPatient": true,
  "antwortOptionen": []
}


### Message vom Arzt senden
POST http://localhost:8080/session/{SessionKey}/message
Content-Type: application/json

{
  "nachrichtenText": "Haben Sie Fieber?",
  "videoPfad": "https://cdn.jwplayer.com/videos/ZHj6MOWJ-3uRaWXX3.mp4",
  "fromPatient": true,
  "antwortOptionen": ["Ja", "Nein"]
}

### Vorgefertigte Fragen zum spezifischen Begriff suchen
GET http://localhost:8080/messageRepository?tag={Begriff};

###
